"""governed -- a small, explicit framework for goal-directed LLM agents.

Quickstart::

    from governed import Agent, AgentConfig
    from governed.llm import AnthropicClient

    agent = Agent(AgentConfig(
        llm=AnthropicClient(model="claude-sonnet-5"),
        workspace="./workspace",
        trace_path="./traces/run.jsonl",
    ))
    result = agent.run("Profile data/sales.csv and name the top 3 regions by revenue.")
    print(result.status, result.confidence)
    print(result.answer)
"""

from __future__ import annotations

from .agent import Agent, BudgetExceeded, Cancelled, RunResult
from .config import (
    AgentConfig,
    ApprovalPolicy,
    Budget,
    FeatureToggleConfig,
    ObservabilityConfig,
    auto_approve,
    cli_approve,
    deny_all,
)
from .contracts import ContractViolation, Evaluation, Phase, Plan, PlanStep
from .llm import (
    LLMClient,
    LLMConfig,
    LLMResponse,
    Message,
    ProviderPolicy,
    ProviderPolicyViolation,
    ScriptedClient,
    ToolCall,
    Usage,
    register_provider,
    resolve_llm,
)
from .memory import (
    PRICING,
    PRICING_AS_OF,
    CallCost,
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitOpen,
    CompactionConfig,
    CostConfig,
    CostLedger,
    InMemoryStore,
    JSONFileStore,
    ModelPricing,
    RecursiveCompactor,
    SessionState,
    StateStore,
    compaction_for,
    resolve_pricing,
)
from .observability import (
    GENESIS_HASH,
    AuditReport,
    ConsoleSink,
    DecisionLedger,
    DecisionLedgerConfig,
    DecisionLedgerSink,
    DecisionLedgerStore,
    DecisionRecord,
    Event,
    EventType,
    HttpDecisionLedgerSink,
    HttpEventSink,
    HttpTransport,
    InMemoryDecisionLedger,
    IterationSummary,
    JSONLDecisionLedger,
    JSONLSink,
    LLMCallStats,
    LoggingSink,
    OTelDecisionLedgerSink,
    OTelEventSink,
    SafetyStats,
    SessionTiming,
    TamperDetected,
    TelemetryCollector,
    ToolCallStats,
    TraceLogger,
    build_audit_report,
    default_http_transport,
    export_decisions,
    otlp_kv,
    otlp_log_record,
    otlp_resource_logs,
    otlp_value,
    read_trace,
    trace_to_markdown,
    verify_chain,
)
from .security import (
    AllowTierApprover,
    ApprovalDecision,
    ApprovalRequest,
    Approver,
    CategoryPolicy,
    ContentSafetyScanner,
    DenyAllApprover,
    DestructiveCommandScanner,
    Finding,
    Gateway,
    GovernancePolicy,
    GovernanceViolation,
    GuardedRegistry,
    GuardrailConfig,
    InjectionScanner,
    KeywordSafetyProvider,
    LLMSafetyProvider,
    PIIScanner,
    RiskPolicy,
    RiskTier,
    SafetyProvider,
    SafetyVerdict,
    SecretExfiltrationScanner,
    SelfModificationGuard,
    SemanticInjectionScanner,
    Severity,
    TerminalApprover,
    WebhookApprover,
)
from .skills import (
    Skill,
    SkillConfig,
    SkillLibrary,
    SkillSource,
    register_skill_source,
    registered_skill_sources,
    resolve_skills,
)
from .tools import (
    BUILTIN_TOOLS,
    BackendTimeout,
    BackendUnavailable,
    CodeExecutionTool,
    DataAnalysisTool,
    DockerCodeExecutionBackend,
    ExecResult,
    ExecutionBackend,
    FileSystemTool,
    LoadSkillTool,
    ScratchpadTool,
    SubmitTool,
    SubprocessBackend,
    Tool,
    ToolConfig,
    ToolContext,
    ToolError,
    ToolErrorCode,
    ToolExecutionError,
    ToolFactory,
    ToolRegistry,
    ToolResult,
    ToolSafety,
    ToolSpec,
    default_tools,
    register_tool,
    registered_tool_names,
    resolve_tools,
)

__version__ = "0.2.0"

__all__ = [
    "__version__",
    # core
    "Agent",
    "AgentConfig",
    "RunResult",
    "Budget",
    "BudgetExceeded",
    "Cancelled",
    "ApprovalPolicy",
    "auto_approve",
    "cli_approve",
    "deny_all",
    "ObservabilityConfig",
    "FeatureToggleConfig",
    # contracts
    "Phase",
    "Plan",
    "PlanStep",
    "Evaluation",
    "ContractViolation",
    # llm
    "LLMClient",
    "LLMConfig",
    "LLMResponse",
    "Message",
    "ToolCall",
    "Usage",
    "ScriptedClient",
    "register_provider",
    "resolve_llm",
    "ProviderPolicy",
    "ProviderPolicyViolation",
    # tools
    "Tool",
    "ToolConfig",
    "ToolContext",
    "ToolResult",
    "ToolSpec",
    "ToolSafety",
    "ToolError",
    "ToolErrorCode",
    "ToolExecutionError",
    "ToolRegistry",
    "ToolFactory",
    "default_tools",
    "resolve_tools",
    "register_tool",
    "registered_tool_names",
    "BUILTIN_TOOLS",
    "FileSystemTool",
    "CodeExecutionTool",
    "ExecutionBackend",
    "SubprocessBackend",
    "DockerCodeExecutionBackend",
    "ExecResult",
    "BackendTimeout",
    "BackendUnavailable",
    "DataAnalysisTool",
    "SubmitTool",
    "ScratchpadTool",
    "LoadSkillTool",
    # memory
    "SessionState",
    "StateStore",
    "InMemoryStore",
    "JSONFileStore",
    "CompactionConfig",
    "RecursiveCompactor",
    "compaction_for",
    # cost + circuit breaker
    "CostLedger",
    "CostConfig",
    "CallCost",
    "ModelPricing",
    "PRICING",
    "PRICING_AS_OF",
    "resolve_pricing",
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitOpen",
    # guardrails
    "GuardrailConfig",
    "Gateway",
    "GuardedRegistry",
    "RiskTier",
    "RiskPolicy",
    "Severity",
    "Finding",
    "InjectionScanner",
    "SecretExfiltrationScanner",
    "PIIScanner",
    "DestructiveCommandScanner",
    "SelfModificationGuard",
    "SemanticInjectionScanner",
    "Approver",
    "ApprovalRequest",
    "ApprovalDecision",
    "TerminalApprover",
    "WebhookApprover",
    "AllowTierApprover",
    "DenyAllApprover",
    # governance
    "GovernancePolicy",
    "GovernanceViolation",
    # content safety (Responsible AI execution layer)
    "ContentSafetyScanner",
    "SafetyProvider",
    "SafetyVerdict",
    "CategoryPolicy",
    "KeywordSafetyProvider",
    "LLMSafetyProvider",
    # observability
    "Event",
    "EventType",
    "TraceLogger",
    "ConsoleSink",
    "JSONLSink",
    "LoggingSink",
    "read_trace",
    "trace_to_markdown",
    "AuditReport",
    "IterationSummary",
    "build_audit_report",
    # decision ledger
    "GENESIS_HASH",
    "DecisionLedger",
    "DecisionLedgerConfig",
    "DecisionLedgerSink",
    "DecisionLedgerStore",
    "DecisionRecord",
    "HttpDecisionLedgerSink",
    "InMemoryDecisionLedger",
    "JSONLDecisionLedger",
    "OTelDecisionLedgerSink",
    "TamperDetected",
    "export_decisions",
    "verify_chain",
    # monitoring / event-trace exporters (Splunk, Datadog, New Relic,
    # Dynatrace via HTTP; any OTel-compatible backend via OTLP/HTTP)
    "HttpEventSink",
    "OTelEventSink",
    "HttpTransport",
    "default_http_transport",
    "otlp_kv",
    "otlp_log_record",
    "otlp_resource_logs",
    "otlp_value",
    # telemetry
    "TelemetryCollector",
    "LLMCallStats",
    "ToolCallStats",
    "SessionTiming",
    "SafetyStats",
    # skills
    "Skill",
    "SkillConfig",
    "SkillLibrary",
    "SkillSource",
    "resolve_skills",
    "register_skill_source",
    "registered_skill_sources",
]
